FROM node:18.6.0-alpine3.15

MAINTAINER Christoph Linse

RUN apk --no-cache add --virtual .builds-deps build-base python3 python3-dev py3-pip && \
    echo "echo http://dl-cdn.alpinelinux.org/alpine/latest-stable/main" >> /etc/apk/repositories && \
    echo echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories && \
    apk update && apk upgrade && \
    apk add linux-headers && \
    pip3 install --upgrade pip

RUN pip3 install RPi.GPIO rpi_ws281x adafruit-circuitpython-neopixel
