FROM node:16

MAINTAINER Christoph Linse

#ARG NODE_VERSION

RUN apt update -y && \
    apt install -y sudo && \
    sudo npm install -g @angular/cli @angular-devkit/build-angular:browser

ENTRYPOINT ["npm"]
